name: Publish 🚀

env:
  AZURE_WEBAPP_NAME: ASP-SRV
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./ASP_APP.csproj
        
      - name: Build
        run: dotnet build ./ASP_APP.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./ASP_APP.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
